<a href="<?= $this->url("/building/list") ?>">Back To List</a>

<form method="post" action="<?= $this->url(sprintf("/building/%d", $building->id)) ?>">
    <?= $this->csrf() ?>
    <div>
        <label>ID</label>
        <input type="number" readonly="readonly" placeholder="Auto Generated" name="id" value="<?= $building->id ?>" />
    </div>
    <div>
        <label>ID City</label>
        <input type="number" name="id_city" value="<?= $building->id_city ?>" />
    </div>
    <div>
        <label>Building Name</label>
        <input type="text" name="building_name" value="<?= $building->building_name ?>" />
    </div>
    <div>
        <label>location</label>
        <input type="text" name="location" value="<?= $building->location ?>" />
    </div>
    <div>
        <label>Postal Code</label>
        <input type="text" name="postal_code" value="<?= $building->postal_code ?>" />
    </div>
    asdasd
    <div>
        <label>Address</label>
        <input type="text" name="address" value="<?= $building->address ?>" />
    </div>
    <div>
        <label>Size</label>
        <input type="text" name="size" value="<?= $building->size ?>" />
    </div>
    <div>
        <label>Height</label>
        <input type="text" name="height" value="<?= $building->height ?>" />
    </div>
    <div>
        <label>Floor Level</label>
        <input type="number" name="floor_level" value="<?= $building->floor_level ?>" />
    </div>
    <div>
        <input type="submit" value="Submit" />
</form>