<a href="<?= $this->url("/building/list", ["create" => 1]) ?>">Add New building</a>

<table>
    <thead>
        <tr>
            <th>Building Name</th>
            <th>ID City</th>
            <th>Nama City</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($buildings as $building) : ?>
            <tr>
                <?= sprintf("<td>%s</td>", $building->getBuildingName()); ?>
                <?= sprintf("<td>%s</td>", $building->id_city); ?>
                <?= sprintf("<td>%s</td>", $building->getCity()); ?>
                <td>
                    <ul class="row-action">
                        <?= sprintf("<li><a href=\"%s\">Edit</a></li>", $this->url(sprintf("/building/%d", $building->id))); ?>
                        <?= sprintf("<li><a href=\"%s\">Delete</a></li>", $this->url(sprintf("/building/%d", $building->id), ["delete" => 1])); ?>
                    </ul>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>