<a href="<?= $this->url("/building/list", ["action" => "create"]) ?>">Add New building</a>

<table>
    <thead>
        <tr>
            <th>Building Name</th>
            <th>ID City</th>
            <th>Location</th>
            <th>Postal Code</th>
            <th>Address</th>
            <th>Size</th>
            <th>Height</th>
            <th>Floor Level</th>
            <th>Action</th>
            <th>Nama City</th>
        </tr>
    </thead>
    <tbody>
        <!-- sprintf("<td>%s</td>", $buildings); ?> -->
        <?php foreach ($buildings as $building) : ?>
            <tr>
                <?= sprintf("<td>%s</td>", $building->getBuildingName()); ?>
                <?= sprintf("<td>%s</td>", $building->id_city); ?>
                <?= sprintf("<td>%s</td>", $building->getLocation()); ?>
                <?= sprintf("<td>%s</td>", $building->getPostalCode()); ?>
                <?= sprintf("<td>%s</td>", $building->getAddress()); ?>
                <?= sprintf("<td>%s</td>", $building->getSize()); ?>
                <?= sprintf("<td>%s</td>", $building->getHeight()); ?>
                <?= sprintf("<td>%s</td>", $building->getFloorLevel()); ?>
                <td>
                    <ul class="row-action">
                        <?= sprintf("<li><a href=\"%s\">Edit</a></li>", $this->url(sprintf("/building/%d", $building->id))); ?>
                        <?= sprintf("<li><a href=\"%s\">Delete</a></li>", $this->url(sprintf("/building/%d", $building->id), ["delete" => 1])); ?>
                    </ul>
                </td>
                <?= sprintf("<td>%s</td>", $cities->city_name); ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>