version: "3.2"

services:
    nginx:
        image: nginx:alpine
        container_name: coba2rizal_nginx_${USERID:-1000}
        ports:
            - ${HTTP_PORT:-8080}:80
        volumes:
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
    app:
        build:
            context: ./docker/php-fpm-ext
            args:
                - PHP_VERSION=${PHP_VERSION:-8.1}
        image: php:${PHP_VERSION:-8.1}-fpm-ext
        container_name: coba2rizal_app_${USERID:-1000}
        command:
            - /bin/bash
            - -c
            - |
              usermod -u ${USERID:-1000} www-data
              groupmod -g ${GROUPID:-1000} www-data
              php-fpm
        environment:
            - DB_USERNAME=coba2rizal
            - DB_PASSWORD=888888
            - DB_DATABASE=coba2rizal
            - DB_HOSTNAME=db
            - DB_PORT=3306
            - DB_DRIVER=pdo_mysql
        volumes:
            - ./coba2rizal:/var/www/html
            - ./usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10.6
        container_name: coba2rizal_db_${USERID:-1000}
        ports:
            - ${MYSQL_PORT:-3306}:3306
        environment:
            - MYSQL_ROOT_PASSWORD=888888
            - MYSQL_USER=coba2rizal
            - MYSQL_PASSWORD=888888
            - MYSQL_DATABASE=coba2rizal
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        healthcheck:
            test:
                - "CMD"
                - "mysqladmin"
                - "ping"
                - "--user=coba2rizal"
                - "--password=888888"
                - "-h"
                - "localhost"
            timeout: 5s
            retries: 10
        restart: unless-stopped
