<a href="<?= $this->url("/room/list") ?>">Back To List</a>

<form method="post" action="<?= $this->url(sprintf("/room/%d", $room->id)) ?>">
    <?= $this->csrf() ?>
    <div>
        <label>ID</label>
        <input type="text" readonly="readonly" placeholder="Auto Generated" name="id" value="<?= $room->id ?>" />
    </div>
    <div>
        <label>ID Building</label>
        <input type="text" name="id_building" value="<?= $room->id_building ?>" />
    </div>
    <div>
        <label>ID Floor</label>
        <input type="text" name="id_floor" value="<?= $room->id_floor ?>" />
    </div>
    <div>
        <label>Room Name</label>
        <input type="text" name="room_name" value="<?= $room->room_name ?>" />
    </div>
    <div>
        <label>Room Status</label>
        <input type="text" name="room_status" value="<?= $room->room_status ?>" />
    </div>
    <div>
        <input type="submit" value="Submit" />
</form>