<a href="<?= $this->url("/slot/list") ?>">Back To List</a>

<form method="post" action="<?= $this->url(sprintf("/slot/%d", $slot->id)) ?>">
    <?= $this->csrf() ?>
    <div>
        <label>ID</label>
        <input type="text" readonly="readonly" placeholder="Auto Generated" name="id" value="<?= $slot->id ?>" />
    </div>
    <div>
        <label>ID Shelf</label>
        <input type="number" name="id_shelf" value="<?= $slot->id_shelf ?>" />
    </div>
    <div>
        <label>ID Unit</label>
        <input type="number" name="id_unit" value="<?= $slot->id_unit ?>" max="16" />
    </div>
    <div>
        <label>Slot Name</label>
        <input type="text" name="slot_name" value="<?= $slot->slot_name ?>" />
    </div>
    <div>
        <label>Status</label>
        <select name="status" id="status">
            <option value="">--- Choose a Status ---</option>
            <option value="Full">Full</option>
            <option value="Avalaible">Avalaible</option>
        </select>
    </div>
    <div>
        <input type="submit" value="Submit" />
</form>