<a href="<?= $this->url("/slot/list", ["create" => 1]) ?>">Add New Slot</a>
<a href="<?= $this->url("/slot/liststatus", ["status"]) ?>">List Status</a>
<table>
    <thead>
        <tr>
            <th>ID Shelf</th>
            <th>Slot Name</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($slots as $slot) : ?>
            <tr>
                <?= sprintf("<td>%s</td>", $slot->id_shelf); ?>
                <?= sprintf("<td>%s</td>", $slot->slot_name); ?>
                <?= sprintf("<td>%s</td>", $slot->status); ?>
                <td>
                    <ul class="row-action">
                        <?= sprintf("<li><a href=\"%s\">Edit</a></li>", $this->url(sprintf("/slot/%d", $slot->id))); ?>
                        <?= sprintf("<li><a href=\"%s\">Delete</a></li>", $this->url(sprintf("/slot/%d", $slot->id), ["delete" => 1])); ?>
                    </ul>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>